{% set name = "scienceplots" %}
{% set version = "2.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 51ad98c420e499d3284d07b6447a4b3aedd8ec122aca39ba91c58205226c408a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - matplotlib-base
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base

test:
  imports:
    - scienceplots
  commands:
    - pip check
    - python -c "import matplotlib.pyplot as plt; import scienceplots; plt.style.use('science')"
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/garrettj403/SciencePlots/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Matplotlib styles for scientific plotting
  description: |
    This repo has Matplotlib styles to format your figures for scientific
    papers, presentations and theses.
  doc_url: https://github.com/garrettj403/SciencePlots/
  dev_url: https://github.com/garrettj403/SciencePlots/

extra:
  recipe-maintainers:
    - jan-janssen
