{% set name = "scienceplots" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SciencePlots-{{ version }}.tar.gz
  sha256: efee11d664029e2da1c634addd961972633d16a2d9a30b64331b10ee6c8ba2f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - matplotlib-base
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - python >=3.6

test:
  commands:
    - pip check
    - python -c "import matplotlib.pyplot as plt; import scienceplots; plt.style.use('science')"
  requires:
    - pip

about:
  home: https://github.com/garrettj403/SciencePlots/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Matplotlib styles for scientific plotting
  description: |
    This repo has Matplotlib styles to format your figures for scientific
    papers, presentations and theses.
  doc_url: https://github.com/garrettj403/SciencePlots/
  dev_url: https://github.com/garrettj403/SciencePlots/

extra:
  recipe-maintainers:
    - jan-janssen
